server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/itheima?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: abc15976582078
    driver-class-name: com.mysql.cj.jdbc.Driver